import Head from "next/head";
import Header from '../components/header'
import Link from 'next/link'
import sessionOptions from '../config/session'
import { withIronSessionSsr } from "iron-session/next";

export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({req}){
      const {user} = req.session
      const props = {}
      if (user){
          props.user = req.session.user
      }
      props.isLoggedIn = !!user
      return {props}
  },
  sessionOptions
)

export default function Home() {
  return (
    <>
      <Head>
        <title>MyReads</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} />
      <main>
        <h1>MyReads Home</h1>
        <p>With MyReads you can search for books, add them to your read list, write notes, and view your notes.</p>
        <Link href="/login">Login</Link>
        <p>or</p>
        <Link href="/signup" >Sign Up</Link>

        <p>If you have already logged in, try</p>
        <Link href='/search'>Searching,</Link>
        <p> </p>
        <Link href='/books'>Viewing your read list,</Link>
        <p>or</p>
        <Link href='/create'>Creating a note!</Link>
      </main>
    </>
  );
}
