import Head from "next/head";
import Header from '../components/header'
import Link from 'next/link'
import sessionOptions from '../config/session'
import { withIronSessionSsr } from "iron-session/next";

export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({req}){
      const {user} = req.session
      const props = {}
      if (user){
          props.user = req.session.user
      }
      props.isLoggedIn = !!user
      return {props}
  },
  sessionOptions
)

export default function Home() {
  return (
    <>
      <Head>
        <title>MyReads</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} />
      <main className={`${styles.main}`}>
        <h1>MyReads Home</h1>
        <p>With MyReads you can search for books, add them to your read list, write notes, and view your notes.</p>
       {/* Put it so that if logged in, see to search or create a note, and if logged out see those */}
        <Link href="/login">Login</Link>
        <p>or</p>
        <Link href="/signup" >Sign Up</Link>
      </main>
    </>
  );
}
